### ISSUE TITLE
Working perfectly for my Apple IIe and wico joystick 16-pin Apple joystick

### ISSUE THREAD

**Issue by jaffa225** [ppelleti/A2JoystickAdapter#2]
I just wanted to thank you, and didn't know of a better way.  I was worried that it might loosen over time, but the back of my Apple IIe rarely is moved.  So, although my other joystick secures with the single screw it still has, this seems good enough for my purpose.  Also, I could just add screws since my connector came without them, but I'm lazy. ;)  Thanks again!

**Comment by mignon-p** [comment]
Thanks for your kind words!  It's great to know that someone else is finding this useful!

I can also be contacted [here](https://funwithsoftware.org/contact.html).
